# Generated by Django 2.2.4 on 2019-08-07 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(verbose_name='date published')),
                ('body', models.TextField()),
                ('sender', models.CharField(max_length=150)),
                ('receiver', models.CharField(max_length=150)),
            ],
        ),
    ]
