# Generated by Django 2.2.4 on 2019-08-08 02:15

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('hosting', '0002_auto_20190808_0134'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='creator',
        ),
        migrations.AlterField(
            model_name='room',
            name='detail',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='end_date',
            field=models.DateField(default=datetime.datetime(2019, 8, 8, 2, 15, 33, 821640, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='room',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='room',
            name='image3',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='room',
            name='start_date',
            field=models.DateField(default=datetime.datetime(2019, 8, 8, 2, 15, 33, 821640, tzinfo=utc)),
        ),
    ]
