# Generated by Django 2.2.4 on 2019-08-08 03:18

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('hosting', '0004_auto_20190808_1124'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='title',
            field=models.CharField(default=' ', max_length=50),
        ),
        migrations.AlterField(
            model_name='room',
            name='end_date',
            field=models.DateField(default=datetime.datetime(2019, 8, 8, 3, 18, 38, 210965, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='room',
            name='start_date',
            field=models.DateField(default=datetime.datetime(2019, 8, 8, 3, 18, 38, 210965, tzinfo=utc)),
        ),
    ]
