# Generated by Django 2.2.4 on 2019-08-08 04:59

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('hosting', '0005_auto_20190808_1218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='end_date',
            field=models.DateField(default=datetime.datetime(2019, 8, 8, 4, 59, 39, 554867, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='room',
            name='start_date',
            field=models.DateField(default=datetime.datetime(2019, 8, 8, 4, 59, 39, 554867, tzinfo=utc)),
        ),
    ]
