# Generated by Django 2.2.4 on 2019-08-09 15:13

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('hosting', '0007_auto_20190808_1405'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='end_date',
            field=models.DateField(default=datetime.datetime(2019, 8, 9, 15, 13, 46, 179289, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='room',
            name='period',
            field=models.IntegerField(blank=True, default=-1),
        ),
        migrations.AlterField(
            model_name='room',
            name='start_date',
            field=models.DateField(default=datetime.datetime(2019, 8, 9, 15, 13, 46, 179289, tzinfo=utc)),
        ),
    ]
