# Generated by Django 2.2.4 on 2019-08-09 15:53

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('hosting', '0008_auto_20190810_0013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='end_date',
            field=models.DateField(default=datetime.datetime(2019, 8, 9, 15, 53, 28, 615927, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='room',
            name='start_date',
            field=models.DateField(default=datetime.datetime(2019, 8, 9, 15, 53, 28, 615927, tzinfo=utc)),
        ),
    ]
