# Generated by Django 2.2.3 on 2019-07-20 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('gender', models.IntegerField()),
                ('university', models.IntegerField()),
                ('major', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('rent_type', models.IntegerField()),
                ('roomate_num', models.IntegerField()),
                ('building_type', models.IntegerField()),
                ('period', models.IntegerField()),
                ('cost', models.IntegerField()),
                ('university', models.IntegerField()),
                ('gender', models.IntegerField()),
                ('addr_gu', models.CharField(max_length=4)),
                ('addr_dong', models.CharField(max_length=5)),
                ('image1', models.ImageField(upload_to='images/')),
                ('image2', models.ImageField(upload_to='images/')),
                ('image3', models.ImageField(upload_to='images/')),
                ('detail', models.TextField()),
            ],
        ),
    ]
