# Generated by Django 2.2.3 on 2019-07-20 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('browse', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='addr_gu',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='room',
            name='rent_type',
            field=models.CharField(max_length=10),
        ),
    ]
