# Generated by Django 2.2.3 on 2019-08-06 05:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('browse', '0002_auto_20190720_1637'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Member',
        ),
        migrations.DeleteModel(
            name='Room',
        ),
    ]
